In [8]:
import pytest
import torch

In [4]:
torch.ones((2,3))*3

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [5]:
A = torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

In [6]:
A*A

tensor([[ 1,  4],
        [ 9, 16]])

In [15]:
A = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
B = torch.tensor([0.5, 0.5, 0.5, 1.0])
with pytest.raises(RuntimeError):
    calculate_elementwise_product(A, B)

In [10]:
A*B

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [14]:
def calculate_elementwise_product(A, B):
    return A*B

In [17]:
X = torch.tensor([[1.0, 2.0, 3.0]])
W = torch.tensor([[0.5, 0.5, 0.5]])
torch.matmul(X, W.T)

tensor([[3.]])

In [18]:
b = torch.tensor(-1.5)
torch.matmul(X, W.T) + b

tensor([[1.5000]])

In [22]:
torch.tensor(1.5)

tensor(1.5000)

In [25]:
assert torch.matmul(X, W.T) + b == torch.tensor(1.5)